version: 2.1

orbs:
  newman: postman/newman@1.0.0
  
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/29f49dd89b4de73b8afb 

workflows:
  example-workflow:
    jobs:
      - example-job